name: Publish Snapshot
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build the snapshot from'
        required: true
        default: 'dev'
jobs:
  snapshot-check:
    needs: test
    outputs:
      is_snapshot: ${{ steps.snapshot_check.outputs.is_snapshot }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for Snapshot
        id: snapshot_check
        run: |
          version=$(grep 'ThisBuild / version :=' build.sbt | cut -d '"' -f 2)
          if [[ $version == *"-SNAPSHOT" ]]; then
            echo "::set-output name=is_snapshot::true"
          else
            echo "::set-output name=is_snapshot::false"
          fi
  publish-snapshot:
    needs: snapshot-check
    if: ${{ needs.snapshot-check.outputs.is_snapshot == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Setup SBT
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:21
          apps: sbt
      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --batch --yes --import
      - name: List GPG Keys
        run: gpg --list-keys
      - name: Build and Publish
        run: sbt publishSigned
        env:
          NEXUS_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
