name: Pull Request
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup SBT
      uses: coursier/setup-action@v1
      with:
        jvm: temurin:21
        apps: sbt
    - name: Build and Test
      run: >-
        sbt -v +test
        'avro2s2_12/publishLocal'
        'project sbtAvro2s2_12'
        'set Compile / packageBin / publishArtifact := true'
        'scripted native-enums/regressions standard/standard'
